### ISSUE TITLE
triangulate not found (import)

### ISSUE THREAD

**Issue by Steven-LeMoal** [SergeiShumilin/differentiable-voronoi#1]
First, great work. 

I pip install differentiable_voronoi and tried to import differentiable_voronoi.triangulate but I got that it did not find it.

Solution (for me): modify _init_.py to include triangulate 

from
---> from .differentiable_voronoi import differentiable_voronoi

to
---> from .differentiable_voronoi import differentiable_voronoi, triangulate

**Comment by SergeiShumilin** [comment]
Steven, thank you very much.

Added in the last commit.
